Add `-Zmiri-env-set` to set environment variables without modifying the host environment
rust-lang/miri pull request #3493
Opened 2024-04-19 21:11 UTC by eduardosm

This option allows to pass environment variables to the interpreted program without needing to modify the host environment (which may have undesired effects in some cases).

2024-04-19 21:16 UTC, RalfJung commented
Doesn't rustc have some flag to sent env vars nowadays? Should we just reuse that instead of adding our own?

2024-04-19 21:30 UTC, eduardosm commented
I'm not aware of such flag

2024-04-20 06:20 UTC, RalfJung commented
https://github.com/rust-lang/compiler-team/issues/653 was the decision to add it. Tracking issue is at https://github.com/rust-lang/rust/issues/118372, so it seems to have been implemented.

2024-04-20 11:00 UTC, eduardosm commented
Do we want the same flag for compile-time `env!` and run-time `std::env::var`?

2024-04-21 20:24 UTC, RalfJung commented on README.md
> +  be used multiple times to set several variables. If `-Zmiri-disable-isolation` is set, values set
```suggestion
  be used multiple times to set several variables. If `-Zmiri-disable-isolation` or `-Zmiri-env-forward` is set, values set
```

2024-04-21 20:24 UTC, RalfJung commented on tests/pass/shims/env/var-set.rs
> +// Test both a value set and unset in the host.
```suggestion
// Test a value set on the host (MIRI_ENV_VAR_TEST) and one that is not.
```

2024-04-21 20:25 UTC, RalfJung commented
> Do we want the same flag for compile-time `env!` and run-time `std::env::var`?

Fair, I guess it makes sense to treat them separately.

2024-04-23 09:16 UTC, oli-obk requested changes

2024-04-23 09:16 UTC, oli-obk commented on README.md
> +* `-Zmiri-env-set=<var>=<value>` sets the `var` environment variable to `value` in the interpreted.
```suggestion
* `-Zmiri-env-set=<var>=<value>` sets the `var` environment variable to `value` in the interpreted program.
```

2024-04-23 09:17 UTC, oli-obk approved these changes

2024-04-23 09:17 UTC, oli-obk commented
@bors r+

2024-04-23 09:49 UTC, merged