solaris/illumos localtime_r / clock_getime support enabled.
rust-lang/miri pull request #3614
Opened 2024-05-18 22:16 UTC by devnexen

clock_gettime support CLOCK_REALTIME/CLOCK_MONOTONIC clockid_t. localtime_r is supported only tm struct is more limited than other
 supported platforms.

2024-05-19 12:23 UTC, devnexen commented
@rustbot ready

2024-05-22 09:22 UTC, oli-obk requested changes

2024-05-22 09:22 UTC, oli-obk commented on src/shims/time.rs
> +                // the additional tm_zone/tm_gmtoff fields.
instead of duplicating the core part, can you skip the parts that write the extra fields?

2024-05-22 09:27 UTC, RalfJung commented on tests/pass-dep/libc/libc-time.rs
> +#[cfg(any(target_os = "linux", target_os = "macos", target_os = "freebsd"))]
Instead of making the import conditional, please remove it entirely and use the fully expanded type name below where `CStr` shows up.

2024-05-22 14:13 UTC, oli-obk commented on src/shims/time.rs
> +                &[("tm_isdst", tm_isdst), ("tm_gmtoff", tm_gmtoff.into())],
```suggestion
                &[("tm_gmtoff", tm_gmtoff.into())],
```

tm_isdst was now written twice

2024-05-22 20:37 UTC, merged